### ISSUE TITLE
Texture data size mismatch when running `glium` example.

### ISSUE THREAD

**Issue by mijoharas** [raymanfx/libv4l-rs#24]
Hey, I'm not digging in to the example, so I'm not sure if it's something to worry about, but running the glium example I get the following error:

```
Using device: /dev/video0

Active format:
width          : 640
height         : 480
fourcc         : YUYV
field          : progressive
stride         : 1280
size           : 614400
colorspace     : sRGB
quantization   : default
transfer       : default transfer function

Active parameters:
capabilities : TIME_PER_FRAME
modes        : (empty)
interval     : 1/30 [s]

thread 'main' panicked at 'Texture data size mismatch', /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.27.0/src/texture/any.rs:148:13
stack backtrace:
   0: std::panicking::begin_panic
             at /home/michael/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
   1: glium::texture::any::new_texture
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.27.0/src/texture/any.rs:148:13
   2: glium::texture::texture2d::Texture2d::new_impl
             at ./target/debug/build/glium-aab36beb853d0737/out/textures.rs:2899:95
   3: glium::texture::texture2d::Texture2d::new
             at ./target/debug/build/glium-aab36beb853d0737/out/textures.rs:2862:21
   4: glium::main::{{closure}}
             at ./examples/glium.rs:168:30
   5: winit::platform_impl::platform::sticky_exit_callback
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:698:5
   6: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/mod.rs:274:13
   7: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/mod.rs:390:9
   8: winit::platform_impl::platform::EventLoop<T>::run
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:645:35
   9: winit::event_loop::EventLoop<T>::run
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/event_loop.rs:149:9
  10: glium::main
             at ./examples/glium.rs:161:5
  11: core::ops::function::FnOnce::call_once
             at /home/michael/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
 Thought I'd just let you know.

**Comment by raymanfx** [comment]
This happens because we don't have the means to draw YUV data right now. In the example, you can see we try to ask the camera for RGB at 24 bits per pixel [1].

I should probably add a check to make sure the camera supports RGB3 and bail out if it doesn't.

[1] https://github.com/raymanfx/libv4l-rs/blob/master/examples/glium.rs#L66

**Comment by mijoharas** [comment]
ahhhh... that's makes sense. Thanks!
