### ISSUE TITLE
Unable to build for RISC-V

### ISSUE THREAD

**Issue by whqee** [raymanfx/libv4l-rs#69]
```Rust
error: failed to run custom build command for `v4l2-sys-mit v0.2.0`

Caused by:
  process didn't exit successfully: `/home/whqee/devel/rust/hello_v4l2/target/release/build/v4l2-sys-mit-e9452ce4c76c1710/build-script-build` (exit status: 101)
  --- stderr
  error: unknown target triple 'riscv64gc-unknown-linux-gnu', please use -triple or -arch
  thread 'main' panicked at 'libclang error; possible causes include:
  - Invalid flag syntax
  - Unrecognized flags
  - Invalid flag arguments
  - File I/O errors
  - Host vs. target architecture mismatch
  If you encounter an error missing from this list, please file an issue or a PR!', /home/whqee/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.56.0/src/ir/context.rs:531:15
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
     2: core::panicking::panic_display
               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:147:5
     3: core::panicking::panic_str
               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:131:5
     4: core::option::expect_failed
               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:1924:5
     5: core::option::Option<T>::expect
     6: bindgen::ir::context::BindgenContext::new
     7: bindgen::Bindings::generate
     8: bindgen::Builder::generate
     9: build_script_build::main
    10: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by raymanfx** [comment]
It looks like this is a generic Rust issue related to your toolchain, not this project. Are you able to compile other Rust code at all for the target in question?

**Comment by whqee** [comment]
> It looks like this is a generic Rust issue related to your toolchain, not this project. Are you able to compile other Rust code at all for the target in question?

Yes, it's able to build other Rust code for RISCV.

I upgrade *bindgen*  at v4l2-sys/Cargo.toml 
`
bindgen = "0.65.1"
`

then I successfully built for "--target=riscv64gc-unknown-linux-gnu"
